// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuypR3-kF0yRfixtrA0jABufr8N2tncac',
    appId: '1:557396379524:web:17b72fc39f9041e0627fd1',
    messagingSenderId: '557396379524',
    projectId: 'backend-f6efd',
    authDomain: 'backend-f6efd.firebaseapp.com',
    storageBucket: 'backend-f6efd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj0yh_DjmNCAThzS9CIst1NFcd77enfTc',
    appId: '1:557396379524:android:8e2cb393c71c5aa3627fd1',
    messagingSenderId: '557396379524',
    projectId: 'backend-f6efd',
    storageBucket: 'backend-f6efd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvT-pFLKnRu3tgOtxOeQqvbg0SVhO2euI',
    appId: '1:557396379524:ios:7e5341ac58914f86627fd1',
    messagingSenderId: '557396379524',
    projectId: 'backend-f6efd',
    storageBucket: 'backend-f6efd.firebasestorage.app',
    iosBundleId: 'com.example.backend',
  );
}
